text_file = open('texsst.txt', 'r')
len_of_working = int(text_file.readline())
time_from_last_cleaning = int(text_file.readline())
len_of_seans = int(text_file.readline())
len_of_cleaning = int(text_file.readline())
print(len_of_working, time_from_last_cleaning, len_of_seans, len_of_cleaning)
